import type { RulePreset } from "./types";

export const RULE_PRESETS: RulePreset[] = [
  {
    id: "fundingtraders_2step_pro10",
    label: "FundingTraders 2-Step Pro10",
    firm: "FundingTraders",
    program: "2_step",
    profitTargetChallengePct: 10,
    profitTargetVerificationPct: 5,
    maxDailyLossPct: 5,
    maxLossPct: 10,
    maxLossStyle: "static",
    minTradingDays: 4,
    overnightHold: true,
    weekendHold: true,
    newsRestricted: true,
    bestDayRulePct: null,
    allowedInstruments: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "NAS100", "US30"],
    maxRiskPerTradePct: 0.5,
    notes: [
      "Pro overnight/weekend holds allowed.",
      "Funded: max ~2% risk per idea (desk defaults tighter).",
    ],
  },
  {
    id: "ftmo_2step_swing",
    label: "FTMO 2-Step Swing",
    firm: "FTMO",
    program: "2_step",
    profitTargetChallengePct: 10,
    profitTargetVerificationPct: 5,
    maxDailyLossPct: 5,
    maxLossPct: 10,
    maxLossStyle: "static",
    minTradingDays: 4,
    overnightHold: true,
    weekendHold: true,
    newsRestricted: false,
    bestDayRulePct: null,
    allowedInstruments: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "NAS100", "US30", "GER40"],
    maxRiskPerTradePct: 0.5,
    notes: [
      "Challenge 10% then Verification 5%.",
      "Daily loss 5% from midnight CE(S)T balance.",
      "Max loss 10% static floor from starting balance.",
    ],
  },
  {
    id: "ftmo_2step_standard",
    label: "FTMO 2-Step Standard",
    firm: "FTMO",
    program: "2_step",
    profitTargetChallengePct: 10,
    profitTargetVerificationPct: 5,
    maxDailyLossPct: 5,
    maxLossPct: 10,
    maxLossStyle: "static",
    minTradingDays: 4,
    overnightHold: true,
    weekendHold: false,
    newsRestricted: true,
    bestDayRulePct: null,
    allowedInstruments: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "NAS100"],
    maxRiskPerTradePct: 0.5,
    notes: [
      "Funded Standard: flatten before weekend.",
      "Funded news: ±2 min blackout on restricted events.",
    ],
  },
  {
    id: "ftmo_1step",
    label: "FTMO 1-Step",
    firm: "FTMO",
    program: "1_step",
    profitTargetChallengePct: 10,
    profitTargetVerificationPct: null,
    maxDailyLossPct: 3,
    maxLossPct: 10,
    maxLossStyle: "eod_trailing",
    minTradingDays: null,
    overnightHold: true,
    weekendHold: false,
    newsRestricted: true,
    bestDayRulePct: 50,
    allowedInstruments: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "NAS100"],
    maxRiskPerTradePct: 0.4,
    notes: ["Single phase to funded.", "Best day rule 50% on challenge rewards."],
  },
];

export const ACCOUNT_SIZES = [10000, 25000, 50000, 100000] as const;

export const STEPS = [
  { id: "setup" as const, label: "1 Challenge", short: "Challenge" },
  { id: "connect" as const, label: "2 Platform", short: "Platform" },
  { id: "rules" as const, label: "3 Rules", short: "Rules" },
  { id: "strategy" as const, label: "4 Strategy", short: "Strategy" },
  { id: "desk" as const, label: "5 Concierge", short: "Concierge" },
  { id: "ticket" as const, label: "6 Ticket", short: "Ticket" },
  { id: "active" as const, label: "7 Active", short: "Active" },
  { id: "journal" as const, label: "8 Journal", short: "Journal" },
];

export const STRATEGY_TEMPLATES = [
  {
    id: "london_orb",
    name: "London breakout",
    thesis: "Trade London open break of Asia range on FX majors. 1:2 minimum.",
    sessions: ["London"],
    symbols: ["EURUSD", "GBPUSD", "USDJPY"],
    indicators: [
      { id: "asia_range", label: "Asia high/low", role: "Breakout levels" },
      { id: "session", label: "Session clock", role: "Only London open ±90m" },
      { id: "atr", label: "ATR 14", role: "Stop distance floor" },
    ],
    prechecks: [
      { id: "session", label: "Inside London window", hard: true },
      { id: "range", label: "Clean Asia range defined", hard: true },
      { id: "rr", label: "R:R ≥ 1:2", hard: true },
      { id: "news", label: "No red-folder in next 30m", hard: true },
    ],
    riskCapPct: 0.4,
  },
  {
    id: "ny_continuation",
    name: "NY continuation",
    thesis: "Ride NY trend continuation after London bias confirmed on indices/gold.",
    sessions: ["New York"],
    symbols: ["NAS100", "US30", "XAUUSD"],
    indicators: [
      { id: "structure", label: "HH/HL structure", role: "Trend filter" },
      { id: "vwap", label: "VWAP", role: "Pullback entry" },
      { id: "news", label: "US calendar", role: "Avoid data spikes" },
    ],
    prechecks: [
      { id: "bias", label: "London bias aligned", hard: true },
      { id: "vwap", label: "Pullback to VWAP held", hard: true },
      { id: "rr", label: "R:R ≥ 1:1.5", hard: true },
    ],
    riskCapPct: 0.5,
  },
  {
    id: "gold_session",
    name: "Gold session scalp",
    thesis: "XAUUSD only during London/NY overlap; tight stops, quick targets.",
    sessions: ["London", "New York"],
    symbols: ["XAUUSD"],
    indicators: [
      { id: "levels", label: "Prior day H/L", role: "Liquidity" },
      { id: "momentum", label: "5m momentum", role: "Entry trigger" },
    ],
    prechecks: [
      { id: "symbol", label: "XAUUSD only", hard: true },
      { id: "session", label: "Overlap session", hard: true },
      { id: "spread", label: "Spread acceptable", hard: true },
    ],
    riskCapPct: 0.35,
  },
] as const;

export const DEFAULT_GOVERNANCE = {
  humanConfirmRequired: true,
  autoLiveDisabled: true,
  midfleetRequired: true,
  maxRiskOverridePct: null as number | null,
  blockOnNews: true,
  blockOnDailyBufferBelowR: 1,
  paperOnly: true,
};
